apps/books/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
  url(r'^$', views.index, name = "index"),
  url(r'^create_book_review/$', views.create_book_review, name = "create_book_review"),
  url(r'^add/$', views.add, name = "add"),
  url(r'^display/(?P<id>\d+)/$', views.display, name = "display"),
  url(r'^new_author/$', views.new_author, name = "new_author"),
  url(r'^add_review$', views.add_review, name = "add_review")
]

apps/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
  url(r'^$', views.index, name = "index"),
  url(r'^create/$', views.create, name = "create"),
  url(r'^login/$', views.login, name = "login"),
  url(r'^logout/$', views.logout, name = "logout"),
  url(r'show/(?P<id>\d+)/', views.show, name = "show")
]

reviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include ("apps.users.urls", namespace = "login_reg")),
    url(r'^users/', include("apps.users.urls", namespace = "users")),
    url(r'^books/', include ("apps.books.urls", namespace = "books")),
    url(r'^admin/', admin.site.urls),
]

apps/books/models.py
from django.db import models

from apps.users.models import *

class BookManager(models.Manager):
  def create_book(self,form):
    import datetime
    author = Author.objects.get(id=form['book_author'])
    user = User.objects.get(id=form['user_id'])
    book = self.create(
      title = form['title'],
      user = user,
      author = author,
      created_at = datetime.datetime.now(),
      updated_at = datetime.datetime.now()
    )
    return book

class Author(models.Model):
  first_name = models.CharField(max_length=255)
  last_name = models.CharField(max_length=255)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

class Book(models.Model):
  title = models.CharField(max_length=255)
  user = models.ForeignKey(User, related_name = "books_added")
  author = models.ForeignKey(Author, related_name = "books")
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  objects = BookManager()

class Review(models.Model):
  review = models.TextField()
  rating = models.IntegerField()
  user = models.ForeignKey(User, related_name = "books_reviewed")
  book = models.ForeignKey(Book, related_name = "book_reviews")
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

apps/users/models.py
from django.db import models

import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
import bcrypt


class UserManager(models.Manager):
  def validate(self, form):
    errors = []
    #name validations
    if len(form['first_name']) < 2:
      errors.append("Invalid First Name!")
    if not form['first_name'].isalpha:
      errors.append("Invalid First Name!")
    if len(form['last_name']) < 2:
      errors.append("Invalid Last Name!")
    if not form['last_name'].isalpha:
      errors.append("Invalid Last Name!")
    #email validations
    if not EMAIL_REGEX.match(form['email']):
      errors.append('Invalid Email Address!')
    try:
      self.get(email=form['email'])
      errors.append("Email already in use!")
    except:
      pass
    #username validations
    try:
      self.get(username=form['username'])
      errors.append("Username already in use!")
    except:
      pass
    #password validations
    if len(form['password']) < 8:
      errors.append("Password must be at least 8 characters!")
    if form['password'] != form['confirm']:
      errors.append("Password DO NOT match!")
    return errors

  def create_user(self, user_data):
    import datetime
    pw_hash = bcrypt.hashpw(user_data['password'].encode(), bcrypt.gensalt())
    user = self.create(
      first_name = user_data['first_name'],
      last_name = user_data['last_name'],
      username = user_data['username'],
      email = user_data['email'],
      password = pw_hash,
      created_at = datetime.datetime.now(),
      updated_at = datetime.datetime.now()
    )
    return user

  def login(self, form):
    errors = []
    try:
      user = self.get(email=form['email'])
      if bcrypt.checkpw(form['password'].encode(),user.password.encode()):
        return(True,user.id)
      else:
        errors.append("Password incorrect!")
        return (False,errors)
    except:
      errors.append("Email does not exist!")
      return(False,errors)

class User(models.Model):
  first_name = models.CharField(max_length=255)
  last_name = models.CharField(max_length=255)
  username = models.CharField(max_length=255)
  email = models.CharField(max_length=255)
  password = models.CharField(max_length=255)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  objects = UserManager()

apps/books/views.py
from django.shortcuts import render, redirect

from apps.users.models import *

from .models import *

def index(request):
  user = User.objects.get(id=request.session['user_id'])
  context = {
    'user_id': user.id,
    'user_first_name': user.first_name,
    'user_last_name': user.last_name,
    'user_username': user.username,
    'books': Book.objects.all(),
    'reviews': Review.objects.all().order_by("-created_at")[0:3]
  }
  return render(request, 'books/index.html',context)

def add(request):

  context = {
    'authors': Author.objects.all(),
    'user_id': User.objects.get(id=request.session['user_id']).id
  }
  return render(request, 'books/newbook.html',context)

def new_author(request):
  import datetime
  author = Author.objects.create(
    first_name = request.POST['author_first_name'],
    last_name = request.POST['author_last_name'],
    created_at = datetime.datetime.now(),
    updated_at = datetime.datetime.now()
  )
  return redirect('/books/add')

def create_book_review(request):
  import datetime
  book = Book.objects.create_book(request.POST)
  review = Review.objects.create(
    review = request.POST['review'],
    rating = request.POST['rating'],
    user = User.objects.get(id=request.POST['user_id']),
    book = Book.objects.get(id=book.id),
    created_at = datetime.datetime.now(),
    updated_at = datetime.datetime.now()
  )
  return redirect('/books/display/' + str(book.id))

def display(request,id):
  book = Book.objects.get(id=id)
  context = {
    'book_id': book.id,
    'book_title': book.title,
    'reviews': book.book_reviews.all
  }
  return render(request,'books/bookdisplay.html',context)

def add_review(request):
  import datetime
  user = User.objects.get(id=request.session['user_id'])
  book = Book.objects.get(id=request.POST['book_id'])
  review = Review.objects.create(
    review = request.POST['review'],
    rating = request.POST['rating'],
    user = user,
    book = book,
    created_at = datetime.datetime.now(),
    updated_at = datetime.datetime.now()
  )
  return redirect('/books/display/' + str(book.id))

apps/users/views.py
from django.shortcuts import render, redirect

from django.contrib import messages

from .models import *

def index(request):
  return render(request, 'users/index.html')

def create(request):
  if request.method != 'POST':
    return redirect('users:index')
  errors = User.objects.validate(request.POST)
  if errors:
    for error in errors:
      messages.error(request, error)
    return redirect('users:index')
  else:
    user = User.objects.create_user(request.POST)
    request.session['user_id'] = user.id
    return redirect('books:index')

def login(request):
  if request.method != 'POST':
    return redirect('users:home')
  valid,response = User.objects.login(request.POST)
  if valid:
    user_id = response
    request.session['user_id'] = response
    return redirect('books:index')
  else:
    errors = response
    if errors:
      for error in errors:
        messages.error(request,error)
    return redirect('users:index')

def logout(request):
  request.session.clear()
  return redirect('users:index')

def show(request,id):
  user = User.objects.get(id=id)
  context = {
    'user_first_name': user.first_name,
    'user_last_name': user.last_name,
    'user_username': user.username,
    'user_email': user.email,
    'books_reviewed': user.books_reviewed.all
  }
  return render(request,'users/showuser.html',context)

apps/books/templates/books/bookdisplay.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'books/css/main.css' %}">
  <title>Book</title>
</head>
<body>
  <div class="jumbotron">
    <nav class = "navbar navbar-light bg-light">
      <a class = "navbar-nav ml-auto"href = "{% url 'books:index' %}"><button class="btn btn-primary">Home</button></a>
    </nav>
    <h1>{{ book_title }}</h1>
    <h5>Reviews</h5>
    <div class="reviews">
      {% for review in reviews%}
        <p> Rating: {{ review.rating }} Stars</p> 
        <p>{{review.review}} - <a href = "/users/show/{{ review.user.id }}">{{ review.user.first_name }}</a></p>
        
    {% endfor %}
    </div>

    <h4>Add Rating/Review</h4>
    <form action="/books/add_review" method="post">
      {% csrf_token %}
      <label for="rating">Rating:</label>
      <select name="rating">
        <option value="1">1 Star</option>
        <option value="2">2 Stars</option>
        <option value="3">3 Stars</option>
        <option value="4">4 Stars</option>
        <option value="5">5 Stars</option>
      </select>
      <br>
      <textarea name="review"cols="30" rows="5"></textarea>
      <br>
      <input type="submit" value="Add Review">
      <input type="hidden" name="book_id" value = "{{ book_id }}">
    </form>

  </div>
</body>
</html>

apps/books/templates/books/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  {% load static %}
  <link rel = "stylesheet" href = "{% static 'books/css/main.css' %}">
  <title>Home</title>
</head>
<body>
  <div class="jumbotron">
     <h3>Welcome {{user_username}}</h3>
     <nav class = "navbar navbar-expand-md navbar-light bg-light">
       <a class = "navbar-nav mr-auto" href = "{% url 'books:add' %}"><button class="btn btn-primary">Add Book and Review</button></a>
        <a class = "navbar-nav ml-auto"href = "{% url 'users:logout' %}"><button class="btn btn-primary">Logout</button></a>
     </nav>
     <br>
    <h4>Recent Reviews</h4>
    {% for review in reviews %}
      <p><a href = "{% url 'books:display' review.book.id %}">{{review.book.title}}</a> {{review.review}} - <a href = "/books/show/{{review.user.id}}">{{review.user.username}}</a></p>
    {% endfor %}
    <br>
    <h5>Books with Reviews</h5>
    {% for book in books %}
      <a href = "/books/display/{{ book.id }} ">{{ book.title }}</a>
      <br>
    {% endfor %}
    <br>
   
   
    
  </div>
</body>
</html>

apps/books/templates/books/newbook.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'books/css/main.css' %}">
  <title>Add Book and Review</title>
</head>
<body>
  <div class="jumbotron">
    <h1>Add a New Book and Review</h1>
    <nav class = "navbar navbar-light bg-light">
      <a class = "nav navbar ml-auto" href = "{% url 'books:index' %}"><button class="btn btn-primary">Home</button></a>
    </nav>
    <br>
    <h4>Don't see the author? Add new author below.</h4>
    <form action="/books/new_author/" method="post">
      {% csrf_token %}
      <label for="author_first_name">First Name:</label>
      <input type="text" name="author_first_name">
      <label for="aurtho_last_name">Last Name</label>
      <input type="text" name="author_last_name">
      <input type="submit" value="Add Author">
    </form>
    <br>
    <form action="/books/create_book_review/" method="post">
      {% csrf_token %}
     
      <label for="book_author">Author: </label>
      <select name="book_author">
        {% for author in authors %}
          <option value="{{author.id}}">{{author.first_name}} {{author.last_name}}</option>
        {% endfor %}
      </select>
      <br>
      <label for="title">Title:</label>
      <input type="text" name="title" id = "new_book_title">
      <br>
      <label for="rating">Rating:</label>
      <select name="rating">
        <option value="1">1 Star</option>
        <option value="2">2 Stars</option>
        <option value="3">3 Stars</option>
        <option value="4">4 Stars</option>
        <option value="5">5 Stars</option>
      </select>
      <br>
      <label for="review">Review:</label><br>
      <textarea name="review" cols="30" rows="5"></textarea>
      <br>
      <input type="hidden" name="user_id" value = "{{user_id}}">
      <input type="submit" value="Add Book and Review">
    </form>
  </div>
</body>
</html>

apps/users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>Login and Registration</title>
</head>
<body>
  <div class="jumbotron">
    <h1>Register</h1>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
    <form action="{% url 'users:create' %}" method="post">
      {% csrf_token %}

      <label for="first_name">First Name:</label>
      <input type="text" name="first_name">
      <br>
      <label for="last_name">Last Name:</label>
      <input type="text" name="last_name">
      <br>
      <label for="username">Username:</label>
      <input type="text" name="username">
      <br>
      <label for="email">Email:</label>
      <input type="text" name="email">
      <br>
      <label for="password">Password:</label>
      <input type="password" name="password">
      <br>
      <label for="confirm">Confirm Password:</label>
      <input type="password" name="confirm">
      <br>
      <input type="submit" value="Register">

    </form>

    <h1>Login</h1>

    <form action="{% url 'users:login' %}" method="post">
      {% csrf_token %}

      <label for="email">Email</label>
      <input type="text" name="email">
      <br>
      <label for="password">Password:</label>
      <input type="password" name="password">
      <br>
      <input type="submit" value="Login">
    </form>
  </div>
</body>
</html>

apps/users/templates/users/showuser.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'books/css/main.css' %}">
  <title>User</title>
</head>
<body>
  <div class="jumbotron">
    <nav class = "navbar navbar-light bg-light">
      <a class = "navbar-nav mr-auto" href = "{% url 'books:index' %}">Home</a>
      <a class = "navbar-nav ml-auto" href = "{% url 'books:add' %}"><button class="btn btn-primary">Add Book and Review</button></a>
    </nav>
    <br>
    <h4>User: {{ user_username }}</h4>
    <h4>Name: {{ user_first_name }} {{ user_last_name }}</h4>
    <h4>Email: {{ user_email }}</h4>
    <br>
    <h5>Reviewed Books:</h5>
    {% for book in books_reviewed %}
      <a href = "/books/display/{{book.book.id}}">{{book.book.title}}</a>
      <br>
    {% endfor %}
    
  </div>
</body>
</html>